# .goreleaser.yaml

version: 2

project_name: slurm_exporter

# Release configuration
release:
  github:
    owner: sckyzo 
  name_template: "{{ .ProjectName }} v{{ .Version }}"

builds:
  - id: slurm_exporter
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
    binary: "{{ .ProjectName }}"
    main: "."
    ldflags:
      - "-s -w"
      - "-X=github.com/prometheus/common/version.Version={{.Version}}"
      - "-X=github.com/prometheus/common/version.Revision={{.Commit}}"
      - "-X=github.com/prometheus/common/version.Branch={{.Branch}}"
      - "-X=github.com/prometheus/common/version.BuildUser={{.Env.BUILD_USER}}"
      - "-X=github.com/prometheus/common/version.BuildDate={{.Env.BUILD_DATE}}"
    env:
      - CGO_ENABLED=0

archives:
  - id: slurm_exporter-release-archive
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"




